[package]
name = "break-eternity-rs"
version = "0.1.1"
edition = "2021"
rust-version = "1.70"
license = "MIT"
description = "Fork of break-eternity: a numerical library to represent numbers as large as 10^^1e308 and as 'small' as 10^-(10^^1e308)."
authors = ["MaddisonM79", "cozyGalvinism <jean@der-capta.in>"]
repository = "https://github.com/MaddisonM79/break-eternity-rs"
homepage = "https://github.com/MaddisonM79/break-eternity-rs"
documentation = "https://docs.rs/break-eternity-rs"
keywords = ["big", "decimal", "bigdecimal", "incremental", "games"]
categories = ["game-development", "science::mathematics"]
readme = "README.md"
exclude = [".gitignore", ".vscode", ".github"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "break_eternity"

[dependencies]
thiserror = "1"
serde = { version = "1", optional = true }
gdnative = { version = "0.11", optional = true }

[features]
default = []
godot = ["gdnative"]
