//! Parity tests against break_eternity.js.
//!
//! Each case in `tests/fixtures/parity.json` is an `(op, a, [b, c, d], result)` record. We
//! parse the operands as Rust `Decimal`s, perform the corresponding op, and assert the result
//! matches the JS reference within tolerance.
//!
//! The fixture was generated by `tests/fixtures/generate.mjs` against
//! `break_eternity.js@2.1.3`. Re-generate with:
//! ```sh
//! cd tests/fixtures && npm install break_eternity.js@2.1.3 && node generate.mjs
//! ```
//!
//! Tolerance
//! ---------
//! `Decimal::approx_eq` uses a relative tolerance: the difference must be no
//! greater than `tol * max(|a.mag|, |b.mag|)`. We use `1e-8` across the board,
//! with a looser `1e-6` for the iterative super-root, penta-log, and small-base
//! `layer_add` searches whose JS reference values carry their own search error.
//!
//! Every case must pass unless it is listed in [`KNOWN_DIVERGENCES`] with a reason.

use break_eternity::{Decimal, LambertBranch, TetrationMode};
use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct Case {
    op: String,
    a: String,
    #[serde(default)]
    b: Option<String>,
    #[serde(default)]
    c: Option<String>,
    #[serde(default)]
    d: Option<String>,
    result: String,
}

/// Classes of cases where the Rust port deliberately differs from break_eternity.js.
///
/// Returns the reason when `case` (with the Rust outcome `got`) is an intended divergence.
fn deliberate_divergence(
    case: &Case,
    a: Decimal,
    b: Option<Decimal>,
    got: Option<Decimal>,
) -> Option<&'static str> {
    let op = case.op.as_str();
    match op {
        // JS returns 0 for `x mod 0`; Rust reports DivisionByZero like every other division.
        "mod" | "mod_floored" if b.is_some_and(|b| b.is_zero()) && got.is_none() => {
            Some("x mod 0 is DivisionByZero (JS returns 0)")
        }
        // JS floored modulo returns ±|b| when a is an exact multiple of b with the opposite
        // sign; number theory (and Python) say 0.
        "mod_floored" if got.is_some_and(|g| g.is_zero()) => {
            let expected: Decimal = case.result.parse().ok()?;
            (b.is_some_and(|b| expected.abs() == b.abs()))
                .then_some("exact multiple with opposite signs is 0 (JS returns ±|b|)")
        }
        // JS short-circuits x.root(0) to x for x in {0, 1}; a zeroth root is 1/0.
        "root" if b.is_some_and(|b| b.is_zero()) && got.is_none() => {
            Some("0th root is DivisionByZero (JS returns x for x in {0, 1})")
        }
        // Upstream refines slog with a step search that, on a base below 1, never sees the
        // probe cross the target and runs off to a height of ~1e27; layer_add and
        // negative-height tetrate then return the base's fixed point instead of the value.
        "layeradd_base" if b.is_some_and(|b| b < Decimal::one()) => {
            Some("layer_add on a base below 1: upstream's slog search runs away")
        }
        "tetrate_neg0_5" if a < Decimal::one() => {
            Some("layer_add on a base below 1: upstream's slog search runs away")
        }
        // slog of a negative value, or of one below 1/9e15, lies within f64 resolution of -1
        // or -2, so the height carries almost no digits and layer_add amplifies whatever the
        // search's last step left. Upstream's 100-step walk and the secant search here stop
        // on different noise. (A base at or below e^(1/e) makes it ill-defined outright.)
        "layeradd_base" | "layeradd10_0_5" | "iteratedlog10_1_5"
            if a.is_negative() || (a.layer() > 0 && a.mag() < 0.0) =>
        {
            Some("layer_add of a negative or sub-1/9e15 value is resolution-limited noise")
        }
        // JS returns 0 for 0 raised to a negative power; that is 1/0.
        "pow" | "root" if a.is_zero() && b.is_some_and(|b| b.is_negative()) && got.is_none() => {
            Some("0^negative is DivisionByZero (JS returns 0)")
        }
        // JS ignores the sign when taking the square root of a negative value above layer 0.
        "sqrt" if a.is_negative() && got.is_none() => Some("sqrt of a negative is OutOfDomain"),
        // Every negative value above layer 0 is a negative integer, i.e. a pole of gamma.
        "gamma" | "factorial" if a.is_negative() && a.layer() > 0 && got.is_none() => {
            Some("gamma/factorial at a negative integer is OutOfDomain")
        }
        _ => None,
    }
}

fn load_cases() -> Vec<Case> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parity.json");
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "tests/fixtures/parity.json not found — run:\n  \
             cd tests/fixtures && npm install break_eternity.js@2.1.3 && node generate.mjs"
        )
    });
    serde_json::from_str(&data).expect("malformed parity.json")
}

const PARITY_TOLERANCE: f64 = 1e-8;
/// Below this magnitude, both sides are treated as zero.
fn near_zero(d: &Decimal) -> bool {
    d.abs() < Decimal::from_finite(1e-12)
}
const SEARCH_TOLERANCE: f64 = 1e-6;

fn tolerance_for(op: &str) -> f64 {
    match op {
        "ssqrt" | "sroot3" | "penta_log10" | "layeradd_base" | "slog2" | "tetrate_payload"
        | "pentate2" => SEARCH_TOLERANCE,
        _ => PARITY_TOLERANCE,
    }
}

fn parse(s: &str) -> Option<Decimal> {
    s.parse::<Decimal>().ok()
}

const A: TetrationMode = TetrationMode::Analytic;
const L: TetrationMode = TetrationMode::Linear;

/// Evaluates one fixture case. `None` means the Rust side reported an error.
fn evaluate(case: &Case, a: Decimal, b: Option<Decimal>) -> Option<Decimal> {
    let one = Decimal::one();
    let ten = Decimal::ten();
    match case.op.as_str() {
        // Unary
        "abs" => Some(a.abs()),
        "neg" => Some(-a),
        "sqrt" => a.checked_sqrt().ok(),
        "cbrt" => Some(a.cbrt()),
        "ln" => a.checked_ln().ok(),
        "log10" => a.checked_log10().ok(),
        "log2" => a.checked_log2().ok(),
        "exp" => Some(a.exp()),
        "gamma" => a.checked_gamma().ok(),
        "factorial" => a.checked_factorial().ok(),
        "recip" => a.checked_recip().ok(),
        "floor" => Some(a.floor()),
        "ceil" => Some(a.ceil()),
        "round" => Some(a.round()),
        "trunc" => Some(a.trunc()),
        "tetrate2" => a.checked_tetrate(2.0, one, A).ok(),
        "tetrate2_5" => a.checked_tetrate(2.5, one, A).ok(),
        "tetrate2_5_linear" => a.checked_tetrate(2.5, one, L).ok(),
        "tetrate1_5" => a.checked_tetrate(1.5, one, A).ok(),
        "tetrate_neg0_5" => a.checked_tetrate(-0.5, one, A).ok(),
        "tetrate_inf" => a.checked_tetrate(f64::INFINITY, one, A).ok(),
        "slog10" => a.checked_slog(ten, A).ok(),
        "slog2" => a.checked_slog(Decimal::two(), A).ok(),
        "slog10_linear" => a.checked_slog(ten, L).ok(),
        "ssqrt" => a.checked_ssqrt().ok(),
        "sroot3" => a.checked_linear_sroot(3.0).ok(),
        "pentate2" => a.checked_pentate(2.0, one, A).ok(),
        "penta_log10" => a.checked_penta_log(ten, A).ok(),
        "lambertw" => a.checked_lambertw().ok(),
        "lambertw_neg1" => a.checked_lambertw_branch(LambertBranch::NonPrincipal).ok(),
        "sinh" => Some(a.sinh()),
        "cosh" => Some(a.cosh()),
        "tanh" => Some(a.tanh()),
        "asinh" => Some(a.asinh()),
        "acosh" => a.checked_acosh().ok(),
        "atanh" => a.checked_atanh().ok(),
        "sin" => Some(a.sin()),
        "cos" => Some(a.cos()),
        "atan" => Some(a.atan()),
        "layeradd10_1" => a.checked_layer_add_10(one, A).ok(),
        "layeradd10_neg1" => a.checked_layer_add_10(-one, A).ok(),
        "layeradd10_0_5" => a.checked_layer_add_10(Decimal::from_finite(0.5), A).ok(),
        "iteratedlog10_2" => a.checked_iteratedlog(ten, 2.0, A).ok(),
        "iteratedlog10_1_5" => a.checked_iteratedlog(ten, 1.5, A).ok(),
        "parse" => Some(a),
        // Binary
        "add" => a.checked_add(&b?).ok(),
        "sub" => a.checked_sub(&b?).ok(),
        "mul" => a.checked_mul(&b?).ok(),
        "div" => a.checked_div(&b?).ok(),
        "pow" => a.checked_pow(&b?).ok(),
        "root" => a.checked_root(&b?).ok(),
        "log" => a.checked_log(&b?).ok(),
        "mod" => a.checked_rem(&b?).ok(),
        "mod_floored" => a.checked_rem_floored(&b?).ok(),
        "tetrate_payload" => a.checked_tetrate(2.0, b?, A).ok(),
        "layeradd_base" => a.checked_layer_add(1.0, b?, A).ok(),
        // 4-ary game helpers: a = resources/items, b = start, c = ratio/add, d = owned
        "afford_geometric" | "sum_geometric" | "afford_arithmetic" | "sum_arithmetic" => {
            let c = parse(case.c.as_deref()?)?;
            let d = parse(case.d.as_deref()?)?;
            let b = b?;
            match case.op.as_str() {
                "afford_geometric" => Decimal::checked_afford_geometric_series(a, b, c, d).ok(),
                "sum_geometric" => Decimal::checked_sum_geometric_series(a, b, c, d).ok(),
                "afford_arithmetic" => Decimal::checked_afford_arithmetic_series(a, b, c, d).ok(),
                _ => Decimal::checked_sum_arithmetic_series(a, b, c, d).ok(),
            }
        }
        _ => None,
    }
}

#[test]
fn js_parity() {
    let cases = load_cases();
    let total = cases.len();
    let mut failures = Vec::new();
    let mut skipped = 0usize;
    let mut known = 0usize;
    let mut known_reasons: std::collections::BTreeMap<&str, usize> =
        std::collections::BTreeMap::new();

    let known_ops: Vec<&str> = [
        "abs",
        "neg",
        "sqrt",
        "cbrt",
        "ln",
        "log10",
        "log2",
        "exp",
        "gamma",
        "factorial",
        "recip",
        "floor",
        "ceil",
        "round",
        "trunc",
        "tetrate2",
        "tetrate2_5",
        "tetrate2_5_linear",
        "tetrate1_5",
        "tetrate_neg0_5",
        "tetrate_inf",
        "slog10",
        "slog2",
        "slog10_linear",
        "ssqrt",
        "sroot3",
        "pentate2",
        "penta_log10",
        "lambertw",
        "lambertw_neg1",
        "sinh",
        "cosh",
        "tanh",
        "asinh",
        "acosh",
        "atanh",
        "sin",
        "cos",
        "atan",
        "layeradd10_1",
        "layeradd10_neg1",
        "layeradd10_0_5",
        "iteratedlog10_2",
        "iteratedlog10_1_5",
        "parse",
        "add",
        "sub",
        "mul",
        "div",
        "pow",
        "root",
        "log",
        "mod",
        "mod_floored",
        "tetrate_payload",
        "layeradd_base",
        "afford_geometric",
        "sum_geometric",
        "afford_arithmetic",
        "sum_arithmetic",
    ]
    .to_vec();

    for case in &cases {
        if !known_ops.contains(&case.op.as_str()) {
            eprintln!("SKIP (unknown op): {}", case.op);
            skipped += 1;
            continue;
        }
        let Some(a) = parse(&case.a) else {
            failures.push(format!("PARSE FAIL: op={} a={:?}", case.op, case.a));
            continue;
        };
        let b = match &case.b {
            Some(s) => match parse(s) {
                Some(v) => Some(v),
                None => {
                    failures.push(format!("PARSE FAIL: op={} b={s:?}", case.op));
                    continue;
                }
            },
            None => None,
        };
        let Some(expected) = parse(&case.result) else {
            failures.push(format!(
                "RESULT PARSE FAIL: op={} result={:?}",
                case.op, case.result
            ));
            continue;
        };

        let got = evaluate(case, a, b);
        if let Some(reason) = deliberate_divergence(case, a, b, got) {
            known += 1;
            *known_reasons.entry(reason).or_default() += 1;
            continue;
        }
        match got {
            // Relative tolerance is meaningless next to zero: JS returns ~1e-16 noise for
            // slog(1) where the exact answer is 0.
            Some(got)
                if got.approx_eq(&expected, tolerance_for(&case.op))
                    || (near_zero(&expected) && near_zero(&got)) => {}
            Some(got) => failures.push(format!(
                "MISMATCH: op={} a={:?} b={:?} expected={} got={got}",
                case.op, case.a, case.b, case.result
            )),
            None => failures.push(format!(
                "RUST ERR: op={} a={:?} b={:?} expected={}",
                case.op, case.a, case.b, case.result
            )),
        }
    }

    let ran = total - skipped - known;
    for f in &failures {
        eprintln!("{f}");
    }
    for (reason, n) in &known_reasons {
        eprintln!("known divergence x{n}: {reason}");
    }
    eprintln!(
        "\nParity: {}/{ran} passed ({} failed, {known} known divergences, {skipped} skipped of {total} total)",
        ran - failures.len(),
        failures.len()
    );

    assert!(
        failures.is_empty(),
        "{} parity cases failed (see stderr above)",
        failures.len()
    );
}
