//! Parity tests against break_eternity.js.
//!
//! Each case in `tests/fixtures/parity.json` is a `(op, a, [b], result)` tuple.
//! We parse the operands as Rust `Decimal`s, perform the corresponding op, and
//! assert the result matches the JS reference within tolerance.
//!
//! The fixture was generated by `tests/fixtures/generate.mjs` against
//! `break_eternity.js@2.1.3`. Re-generate with:
//! ```sh
//! cd tests/fixtures && npm install break_eternity.js && node generate.mjs
//! ```
//!
//! Tolerance
//! ---------
//! `Decimal::approx_eq` uses a relative tolerance: the difference must be no
//! greater than `tol * max(|a.mag|, |b.mag|)`. We use `1e-8` across the board.
//! Transcendental and tetration results may diverge more than this for large
//! layers; divergences are counted and the test fails only if more than 5%
//! of cases fail.

use break_eternity::Decimal;
use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct Case {
    op: String,
    a: String,
    #[serde(default)]
    b: Option<String>,
    result: String,
}

fn load_cases() -> Vec<Case> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parity.json");
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "tests/fixtures/parity.json not found — run:\n  \
             cd tests/fixtures && npm install break_eternity.js && node generate.mjs"
        )
    });
    serde_json::from_str(&data).expect("malformed parity.json")
}

const PARITY_TOLERANCE: f64 = 1e-8;

/// Returns `true` if the operation succeeded and matched; `false` if there was
/// a mismatch. Rust-side errors that should have been JS-side successes are
/// treated as failures (logged to stderr).
fn run_unary(case: &Case, op: impl Fn(&Decimal) -> Option<Decimal>) -> bool {
    let a: Decimal = match case.a.as_str().try_into() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("SKIP (parse fail): op={} a={:?} err={e}", case.op, case.a);
            return true; // not a failure, fixture was skipped
        }
    };
    let expected: Decimal = match case.result.as_str().try_into() {
        Ok(d) => d,
        Err(e) => {
            eprintln!(
                "SKIP (result parse fail): op={} result={:?} err={e}",
                case.op, case.result
            );
            return true;
        }
    };
    match op(&a) {
        Some(got) => {
            let ok = got.approx_eq(&expected, PARITY_TOLERANCE);
            if !ok {
                eprintln!(
                    "FAIL: op={} a={:?} expected={:?} got={:?}",
                    case.op, case.a, case.result, got
                );
            }
            ok
        }
        None => {
            eprintln!(
                "FAIL (Rust err): op={} a={:?} expected={}",
                case.op, case.a, case.result
            );
            false
        }
    }
}

fn run_binary(case: &Case, op: impl Fn(&Decimal, &Decimal) -> Option<Decimal>) -> bool {
    let a: Decimal = match case.a.as_str().try_into() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("SKIP (parse fail a): op={} a={:?} err={e}", case.op, case.a);
            return true;
        }
    };
    let b_str = case.b.as_ref().expect("binary op must have b field");
    let b: Decimal = match b_str.as_str().try_into() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("SKIP (parse fail b): op={} b={:?} err={e}", case.op, b_str);
            return true;
        }
    };
    let expected: Decimal = match case.result.as_str().try_into() {
        Ok(d) => d,
        Err(e) => {
            eprintln!(
                "SKIP (result parse fail): op={} result={:?} err={e}",
                case.op, case.result
            );
            return true;
        }
    };
    match op(&a, &b) {
        Some(got) => {
            let ok = got.approx_eq(&expected, PARITY_TOLERANCE);
            if !ok {
                eprintln!(
                    "FAIL: op={} a={:?} b={:?} expected={:?} got={:?}",
                    case.op, case.a, b_str, case.result, got
                );
            }
            ok
        }
        None => {
            eprintln!(
                "FAIL (Rust err): op={} a={:?} b={:?} expected={}",
                case.op, case.a, b_str, case.result
            );
            false
        }
    }
}

#[test]
fn js_parity() {
    let cases = load_cases();
    let total = cases.len();
    let mut failures = 0usize;
    let mut skipped = 0usize;

    for case in &cases {
        let ok = match case.op.as_str() {
            "abs" => run_unary(case, |a| Some(a.abs())),
            "neg" => run_unary(case, |a| Some(-*a)),
            "sqrt" => run_unary(case, |a| a.checked_sqrt().ok()),
            "ln" => run_unary(case, |a| a.checked_ln().ok()),
            "log10" => run_unary(case, |a| a.checked_log10().ok()),
            "log2" => run_unary(case, |a| a.checked_log2().ok()),
            "exp" => run_unary(case, |a| Some(a.exp())),
            "gamma" => run_unary(case, |a| a.checked_gamma().ok()),
            "factorial" => run_unary(case, |a| a.checked_factorial().ok()),
            "recip" => run_unary(case, |a| {
                // recip = 1 / a; the fixture skips a=0 (JS returns NaN for 0.recip)
                Decimal::from_finite(1.0).checked_div(a).ok()
            }),
            "tetrate2" => run_unary(case, |a| {
                a.checked_tetrate(2.0, Decimal::from_finite(1.0)).ok()
            }),
            "slog10" => run_unary(case, |a| {
                a.checked_slog(10.0, break_eternity::TetrationMode::Analytic).ok()
            }),
            "add" => run_binary(case, |a, b| a.checked_add(b).ok()),
            "sub" => run_binary(case, |a, b| a.checked_sub(b).ok()),
            "mul" => run_binary(case, |a, b| a.checked_mul(b).ok()),
            "div" => run_binary(case, |a, b| a.checked_div(b).ok()),
            "pow" => run_binary(case, |a, b| a.checked_pow(b).ok()),
            other => {
                eprintln!("SKIP (unknown op): {other}");
                skipped += 1;
                true
            }
        };
        if !ok {
            failures += 1;
        }
    }

    let ran = total - skipped;
    let passed = ran - failures;
    eprintln!(
        "\nParity: {passed}/{ran} passed ({failures} failed, {skipped} skipped of {total} total)"
    );

    let fail_ratio = if ran == 0 {
        0.0
    } else {
        failures as f64 / ran as f64
    };

    assert!(
        fail_ratio < 0.05,
        "{:.1}% of parity cases failed (threshold 5%); {failures}/{ran} failing",
        fail_ratio * 100.0
    );
}
